# Advanced Docker Compose with Secrets Support
# Use this for production deployments with enhanced security

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: homelab-wiki-backend
    environment:
      - FLASK_ENV=production
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - DATABASE_URL=${DATABASE_URL:-sqlite:///homelab_wiki.db}
      - LDAP_SERVER=${LDAP_SERVER:-WYK-DC01}
      - LDAP_PORT=${LDAP_PORT:-389}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-DC=homelab,DC=local}
      - LDAP_BIND_DN=${LDAP_BIND_DN:-CN=wikisvc,CN=Users,DC=homelab,DC=local}
      - LDAP_BIND_PASSWORD_FILE=/run/secrets/ldap_password
      - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE:-CN=Users,DC=homelab,DC=local}
      - LDAP_GROUP_SEARCH_BASE=${LDAP_GROUP_SEARCH_BASE:-CN=Groups,DC=homelab,DC=local}
    secrets:
      - secret_key
      - ldap_password
    volumes:
      - wiki_data:/app/data
      - wiki_uploads:/app/uploads
      - wiki_backups:/app/backups
      - wiki_logs:/app/logs
    networks:
      - wiki_network
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homelab-wiki-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - wiki_network
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: postgres:15-alpine
    container_name: homelab-wiki-database
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-homelab_wiki}
      - POSTGRES_USER=${POSTGRES_USER:-wiki_user}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wiki_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: homelab-wiki-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - wiki_network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  ldap_password:
    file: ./secrets/ldap_password.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  wiki_data:
    driver: local
  wiki_uploads:
    driver: local
  wiki_backups:
    driver: local
  wiki_logs:
    driver: local
  postgres_data:
    driver: local

networks:
  wiki_network:
    driver: bridge
